version: "3.9"

services:
  app:
    image: rolandeke/starrtix-api:${ENV}
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    container_name: starrtix-api-${ENV}
    command: >
      sh -c "python manage.py makemigrations User
             python manage.py makemigrations Event
             python manage.py makemigrations blog
             python manage.py makemigrations public_events
             python manage.py migrate User 
             python manage.py migrate Event
             python manage.py migrate blog
             python manage.py migrate public_events
             python manage.py migrate 
             python manage.py collectstatic --skip-checks
             python manage.py createsuperuser --noinput --username $DJANGO_SUPERUSER_USERNAME --email $DJANGO_SUPERUSER_EMAIL
             gunicorn starrtixbackend.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - ./starrtixbackend/.env.development
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DEBUG=${DEBUG}
      - ENVIRONMENT=${ENVIRONMENT}
      - DJANGO_DB_ENGINE=${DJANGO_DB_ENGINE}
      - DJANGO_DB_NAME=${DJANGO_DB_NAME}
      - DJANGO_DB_USER=${DJANGO_DB_USER}
      - DJANGO_DB_PASSWORD=${DJANGO_DB_PASSWORD}
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=${DJANGO_DB_PORT}
    volumes:
      - .:/app
    ports:
      - ${DJANGO_APP_PORT}:${DJANGO_APP_PORT}
    networks:
      - starrtix-net
      - mysql-db-network
      - kenecare-net

volumes:
  starrtix-data-dev:
    name: starrtix-data-dev

networks:
  starrtix-net:
    name: starrtix-net
    driver: bridge
  mysql-db-network:
    name: mysql-db-network
    external: true
  kenecare-net:
    name: kenecare-net
    external: true
