# Generated by Django 5.0.3 on 2024-04-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='freepik.com', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='video',
            field=models.FileField(default='freepik.com', upload_to='videos/'),
        ),
    ]
