# Generated by Django 5.0.3 on 2024-04-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='freepic.com', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='event',
            name='video',
            field=models.FileField(default='freepic.com', upload_to='videos/'),
        ),
    ]
