# Generated by Django 4.2 on 2024-04-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0006_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
