name: deploy

on:
  workflow_run:
    workflows: ["build-and-push-images"]
    types:
      - completed

env:
  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  ENV: "production"

jobs:
  deploy:
    runs-on: ["self-hosted", "scorpion-garage"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop running container
        run: docker stop startix-api-production || true

      - name: Remove application running container
        run: docker rm -f startix-api-production || true

      - name: Remove cached images
        run: docker rmi rolandeke/startix-api:production || true

      - name: Copy application env
        run: cp ~/.env.starrtix ./starrtixbackend/.env

      - name: Run production
        run: make run-prod
